name: list_fm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_mobx: ^2.3.0
  get_it: ^8.2.0
  google_fonts: ^6.3.1
  json_annotation: ^4.9.0
  mobx: ^2.5.0
  mobx_codegen: ^2.7.2
  retrofit: ^4.7.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.0
  json_serializable: ^6.11.0
  retrofit_generator: ^10.0.2

flutter:
  uses-material-design: true
